name: Trigger auto deployment for msdocsflaskwebapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ create-content ]
    paths:
    - '**'
    - '.github/workflows/msdocsflaskwebapp-AutoDeployTrigger-2d22e271-365f-4f00-9faa-f95866434b81.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: msdocstutorialregistry.azurecr.io
          username: ${{ secrets.MSDOCSFLASKWEBAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.MSDOCSFLASKWEBAPP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: msdocstutorialregistry.azurecr.io/msdocs-python-flask-container-web-app:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MSDOCSFLASKWEBAPP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n msdocsflaskwebapp -g msdocspythontutorial --server msdocstutorialregistry.azurecr.io --username  ${{ secrets.MSDOCSFLASKWEBAPP_REGISTRY_USERNAME }} --password ${{ secrets.MSDOCSFLASKWEBAPP_REGISTRY_PASSWORD }}
            az containerapp update -n msdocsflaskwebapp -g msdocspythontutorial --image msdocstutorialregistry.azurecr.io/msdocs-python-flask-container-web-app:${{ github.sha }}
